### ISSUE TITLE
intoduction

### ISSUE THREAD

**Issue by fabriziogiordano** [amitmishrg/code-resume#2]
I see in the code and in the screenshot the word `intoduction`
Is it a typo or is it intentional?
Should it be `introduction`?

**Comment by amitmishrg** [comment]
Hey, Thanks for the notice. 
Its typo will fix asap.

**Comment by amitmishrg** [comment]
Fixed in code. I will update the screenshot in some time.

**Comment by vincentdoerig** [comment]
I have found two more typos: it should be `sketch` instead of seketch [here](https://github.com/amitmishrg/code-resume/blob/cc5d35006d7b38bd8cfc9306233f6b23ddf83361/data/index.js#L62) (twice) and `Progressive` instead of Prograsive [here](https://github.com/amitmishrg/code-resume/blob/cc5d35006d7b38bd8cfc9306233f6b23ddf83361/data/index.js#L55).

**Comment by amitmishrg** [comment]
@vincentdoerig Fixed!
